
[types]

	[types.leaves_type]

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.wood_type]

		[types.wood_type.quark]
			azalea = true
			blossom = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

	[entries.wood_type]

		[entries.wood_type.mcwdoors]
			nether_door = true
			stable_head_door = true
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			cottage_door = true
			four_panel_door = true
			western_door = true
			paper_door = true
			glass_door = true
			beach_door = true
			barn_door = true
			mystic_door = true
			japanese_door = true
			bark_glass_door = true
			classic_door = true
			stable_door = true
			modern_door = true

		[entries.wood_type.mcwlights]
			soul_tiki_torch = true
			tiki_torch = true

		[entries.wood_type.mcwtrpdoors]
			classic_trapdoor = true
			beach_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			glass_trapdoor = true
			barred_trapdoor = true
			tropical_trapdoor = true
			cottage_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			mystic_trapdoor = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			horse_fence = true
			pyramid_gate = true
			stockade_fence = true
			wired_fence = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true
			rope_bridge = true
			log_bridge_middle = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.storagedrawers]
			half_drawers_1 = true
			half_drawers_4 = true
			half_drawers_2 = true
			trim = true
			full_drawers_2 = true
			full_drawers_4 = true
			full_drawers_1 = true

		[entries.wood_type.quark]
			vertical_planks = true
			chest = true
			ladder = true
			post = true
			trapped_chest = true
			bookshelf = true
			stripped_post = true
			vertical_slab = true

		[entries.wood_type.mcwpaths]
			planks_path = true

